title: Hello, world! I'm Tim Donaworth
description: > # this means to ignore newlines until "baseurl:"
  Write an awesome description for your new site here. You can edit this
  line in _config.yml. It will appear in your document head meta (for
  Google search results) and in your feed.xml site description.
permalink: ':title/'
baseurl: "/" # the subpath of your site, e.g. /blog
url: "https://www.donaworth.org" # the base hostname & protocol for your site, e.g. http://example.com
site-twitter: #if your site has a twitter account, enter it here

# Author Settings
author: Tim Donaworth # add your name
author-img: tim-donaworth.jpeg # add your photo
about-author: Security Engineer, Software Engineer, Hacker, Maker and enthusiest of all things two-wheeled. # add description
social-twitter: tdonaworth # add your Twitter handle
social-facebook: # add your Facebook handle
social-github: donaworth-r-d # add your Github handle
social-linkedin: tim-d-33a9834 # add your Linkedin handle
social-email: tim@donaworth.org # add your Email address

# Disqus
discus-identifier: # add your discus identifier

# Tracker
analytics: # Google Analytics

# Build Settings
markdown: kramdown
plugins:
  - jekyll-sitemap
  - jekyll-paginate
  - jemoji

paginate: 8
paginate_path: "/page/:num"

exclude: ["node_modules", "gulpfile.js", "package.json", "yarn.lock"]
